export const json_ar=[
    {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2289.JPG.pagespeed.ic.dMVsydlJIP.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2309.JPG.pagespeed.ic.EhmgsUvSii.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2312.JPG.pagespeed.ic.M9T2SAXgD0.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2316.JPG.pagespeed.ic.xj79g1Cde4.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2320.JPG.pagespeed.ic.baZoGwWI75.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2324.JPG.pagespeed.ic.RsIXPSedRF.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2326.JPG.pagespeed.ic.yrolNhXXnx.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2329.JPG.pagespeed.ic.1aIkj41H_u.webp"
    },
    {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2330.JPG.pagespeed.ic.MSpG3i6Gx_.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2334.JPG.pagespeed.ic.ROtr4M9Jiw.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2335.JPG.pagespeed.ic.6_WaZuqG_9.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2343.JPG.pagespeed.ic.aQhQyt76vg.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2353.JPG.pagespeed.ic.gVNNUVAQM0.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2357.JPG.pagespeed.ic.RrDb8F7xN6.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2316.JPG.pagespeed.ic.xj79g1Cde4.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2320.JPG.pagespeed.ic.baZoGwWI75.webp"
    },
    {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2324.JPG.pagespeed.ic.RsIXPSedRF.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2326.JPG.pagespeed.ic.yrolNhXXnx.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2329.JPG.pagespeed.ic.1aIkj41H_u.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2334.JPG.pagespeed.ic.ROtr4M9Jiw.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2330.JPG.pagespeed.ic.MSpG3i6Gx_.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2334.JPG.pagespeed.ic.ROtr4M9Jiw.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2335.JPG.pagespeed.ic.6_WaZuqG_9.webp"
    },
     {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2343.JPG.pagespeed.ic.aQhQyt76vg.webp"
    },
    {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2353.JPG.pagespeed.ic.gVNNUVAQM0.webp"
    },
    {
        "image":"https://www.mardigrasneworleans.com/constrain/auto/180/uploads/gallery/xDSCN2357.JPG.pagespeed.ic.RrDb8F7xN6.webp"
    }
]